### ISSUE TITLE
Contribute css-sort to MELPA or css-mode.el

### ISSUE THREAD

**Issue by freesteph** [manateelazycat/css-sort#2]
Hi

Thanks a ton for `css-sort`! I was trying to write my own the whole morning then found your code which already does it and in a much nicer way.

Have you considered making it available to MELPA or even into Emacs itself? I think it's such a useful feature that it would be welcome in either.

Cheers.

**Comment by manateelazycat** [comment]
Thanks for message.

I haven't time upload to MELPA and Emacs, just put it here.
